from setuptools import setup, find_packages

setup(
    name='trpp_inserter',
    version='0.1',
    description='Приложение для автоматизации работы с документами',
    author='Zinenko, Kotkov, Bobrov',
    url='bobrovtd/TRPP_BarcodeInserter',
    packages=find_packages(),
    install_requires=[
        'alabaster==1.0.0',
        'anyio==4.7.0',
        'babel==2.17.0',
        'certifi==2024.8.30',
        'chardet==5.2.0',
        'charset-normalizer==3.4.1',
        'colorama==0.4.6',
        'docutils==0.21.2',
        'et_xmlfile==2.0.0',
        'flet==0.25.1',
        'flet-desktop==0.25.1',
        'h11==0.14.0',
        'httpcore==1.0.7',
        'httpx==0.28.1',
        'idna==3.10',
        'imagesize==1.4.1',
        'Jinja2==3.1.6',
        'MarkupSafe==3.0.2',
        'numpy==2.1.3',
        'oauthlib==3.2.2',
        'openpyxl==3.1.5',
        'packaging==24.2',
        'pandas==2.2.3',
        'pillow==11.0.0',
        'Pygments==2.19.1',
        'PyPDF2==3.0.1',
        'python-dateutil==2.9.0.post0',
        'pytz==2024.2',
        'repath==0.9.0',
        'reportlab==4.2.5',
        'requests==2.32.3',
        'roman-numerals-py==3.1.0',
        'setuptools==75.6.0',
        'six==1.17.0',
        'sniffio==1.3.1',
        'snowballstemmer==2.2.0',
        'Sphinx==8.2.3',
        'sphinxcontrib-applehelp==2.0.0',
        'sphinxcontrib-devhelp==2.0.0',
        'sphinxcontrib-htmlhelp==2.1.0',
        'sphinxcontrib-jsmath==1.0.1',
        'sphinxcontrib-qthelp==2.0.0',
        'sphinxcontrib-serializinghtml==2.0.0',
        'typing_extensions==4.12.2',
        'tzdata==2024.2',
        'urllib3==2.3.0',
    ],
    entry_points={
        'console_scripts': [
            'trpp_inserter = main:main',
        ],
    },
)